[build]
target = "index.html"
public_url = "/admin/"

[watch]
ignore = ["dist", "target"]

[serve]
addresses = ["127.0.0.1"]
port = 8091

[[proxy]]
rewrite = "/api/"
backend = "http://localhost:8000/api/"

[[proxy]]
rewrite = "/authorize"
backend = "http://localhost:8000/authorize"

[[proxy]]
rewrite = "/token"
backend = "http://localhost:8000/token"

[[proxy]]
rewrite = "/register"
backend = "http://localhost:8000/register"

[[proxy]]
rewrite = "/passkeys/"
backend = "http://localhost:8000/passkeys/"

[[proxy]]
rewrite = "/login"
backend = "http://localhost:8000/login"

[[proxy]]
rewrite = "/auth/"
backend = "http://localhost:8000/auth/"

[[proxy]]
rewrite = "/verify/"
backend = "http://localhost:8000/verify/"

[[proxy]]
rewrite = "/.well-known/"
backend = "http://localhost:8000/.well-known/"
