package lattice-id:oidc;

world gateway {
    import lattice-id:crypto/password;
    import lattice-id:admin/assets;
    import wasi:config/store@0.2.0-rc.1;
    import wasmcloud:messaging/consumer@0.2.0;
    import lattice-id:notify/email;
    import taika3d:lid/abuse;
    import taika3d:lid/keys;
    import taika3d:lid/authority;
    import taika3d:lid/vault;
}
